[package]
name = "rust_lib"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = "0.9.3"
godot_egui = "0.1.8"
egui = "0.14.2"
egui_demo_lib = "0.14.0"

